<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'XMLTV\Util\DbUtil'                   => __DIR__ . '/src/XMLTV/Util/DbUtil.php',
  'XMLTV\Util\StringUtil'               => __DIR__ . '/src/XMLTV/Util/StringUtil.php',
  'XMLTV\Controller\EpgController'      => __DIR__ . '/src/XMLTV/Controller/EpgController.php',
  'XMLTV\Model\Entity\LiveStream'       => __DIR__ . '/src/XMLTV/Model/Entity/LiveStream.php',
  'XMLTV\Model\Entity\Epg'              => __DIR__ . '/src/XMLTV/Model/Entity/Epg.php',
  'XMLTV\Model\Table\AbstractTable'     => __DIR__ . '/src/XMLTV/Model/Table/AbstractTable.php',
  'XMLTV\Model\Table\EpgTable'          => __DIR__ . '/src/XMLTV/Model/Table/EpgTable.php',
  'XMLTV\Model\Table\LiveStreamsTable'  => __DIR__ . '/src/XMLTV/Model/Table/LiveStreamsTable.php',
  'XMLTV\Model\Service\EpgService'      => __DIR__ . '/src/XMLTV/Model/Service/EpgService.php',
  'XMLTV\Model\Service\AbstractService' => __DIR__ . '/src/XMLTV/Model/Service/AbstractService.php',
  'XMLTV\Options\XmltvOptions'          => __DIR__ . '/src/XMLTV/Options/XmltvOptions.php',
  'XMLTV\Options\EpgOptions'            => __DIR__ . '/src/XMLTV/Options/EpgOptions.php',
  'XMLTV\Module'                        => __DIR__ . '/Module.php',
);
