<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Epg\Listener\ErrorListener'                       => __DIR__ . '/src/Epg/Listener/ErrorListener.php',
  'Epg\Listener\TestListener'                        => __DIR__ . '/src/Epg/Listener/TestListener.php',
  'Epg\Listener\RunTimeListener'                     => __DIR__ . '/src/Epg/Listener/RunTimeListener.php',
  'Epg\Listener\TableListener'                       => __DIR__ . '/src/Epg/Listener/TableListener.php',
  'Epg\Controller\IndexController'                   => __DIR__ . '/src/Epg/Controller/IndexController.php',
  'Epg\Controller\Restful\AbstractRestfulController' => __DIR__ . '/src/Epg/Controller/Restful/AbstractRestfulController.php',
  'Epg\Controller\Restful\EpgController'             => __DIR__ . '/src/Epg/Controller/Restful/EpgController.php',
  'Epg\Controller\AbstractActionController'          => __DIR__ . '/src/Epg/Controller/AbstractActionController.php',
  'Epg\Model\Entity\Epg'                             => __DIR__ . '/src/Epg/Model/Entity/Epg.php',
  'Epg\Model\Service\EpgService'                     => __DIR__ . '/src/Epg/Model/Service/EpgService.php',
  'Epg\Model\Service\AbstractService'                => __DIR__ . '/src/Epg/Model/Service/AbstractService.php',
  'Epg\Model\Table\AbstractTable'                    => __DIR__ . '/src/Epg/Model/Table/AbstractTable.php',
  'Epg\Model\Table\EpgTable'                         => __DIR__ . '/src/Epg/Model/Table/EpgTable.php',
  'Epg\Authentication\Storage\AuthStorage'           => __DIR__ . '/src/Epg/Authentication/Storage/AuthStorage.php',
  'Epg\Module'                                       => __DIR__ . '/Module.php',
);
